### ISSUE TITLE
Error running ShiftAddLLM/Llama-2-70b-wbits2-acc

### ISSUE THREAD

**Issue by viraatdas** [GATECH-EIC/ShiftAddLLM#2]
For

```
CUDA_VISIBLE_DEVICES=0 python3 model/llama.py     ShiftAddLLM/Llama-2-70b-wbits2-acc
```

I'm seeing this error

```
Downloading shards: 100%|██████████████████████| 29/29 [57:38<00:00, 119.25s/it]
Loading checkpoint shards: 100%|████████████████| 29/29 [00:01<00:00, 19.84it/s]
generation_config.json: 100%|██████████████████| 183/183 [00:00<00:00, 2.10MB/s]
LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 8192)
    (layers): ModuleList(
      (0-79): 80 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=8192, out_features=8192, bias=False)
          (k_proj): Linear(in_features=8192, out_features=1024, bias=False)
          (v_proj): Linear(in_features=8192, out_features=1024, bias=False)
          (o_proj): Linear(in_features=8192, out_features=8192, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=8192, out_features=28672, bias=False)
          (up_proj): Linear(in_features=8192, out_features=28672, bias=False)
          (down_proj): Linear(in_features=28672, out_features=8192, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((8192,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((8192,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((8192,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=8192, out_features=32000, bias=False)
)
Downloading readme: 100%|██████████████████| 10.5k/10.5k [00:00<00:00, 52.6MB/s]
Downloading data: 100%|██████████████████████| 733k/733k [00:00<00:00, 17.2MB/s]
Downloading data: 100%|█████████████████████| 6.36M/6.36M [00:00<00:00, 119MB/s]
Downloading data: 100%|██████████████████████| 657k/657k [00:00<00:00, 2.51MB/s]
Generating test split: 100%|█████| 4358/4358 [00:00<00:00, 496085.78 examples/s]
Generating train split: 100%|██| 36718/36718 [00:00<00:00, 938291.37 examples/s]
Generating validation split: 100%|█| 3760/3760 [00:00<00:00, 791338.40 examples/
Traceback (most recent call last):
  File "/home/ubuntu/ShiftAddLLM/model/llama.py", line 273, in <module>
    dataloader, testloader = get_loaders(
  File "/home/ubuntu/ShiftAddLLM/./datautils.py", line 170, in get_loaders
    return get_wikitext2(nsamples, seed, seqlen, model, tokenizer)
  File "/home/ubuntu/ShiftAddLLM/./datautils.py", line 17, in get_wikitext2
    tokenizer = AutoTokenizer.from_pretrained(model, use_fast=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 919, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'ShiftAddLLM/Llama-2-70b-wbits2-acc'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'ShiftAddLLM/Llama-2-70b-wbits2-acc' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
```

**Comment by coco-alen** [comment]
The tokenizer has been uploaded, please try again

**Comment by coco-alen** [comment]
The tokenizer has been uploaded, please try again

**Comment by w32zhong** [comment]
@coco-alen any chance we can download the llama 7B model to try it for a more quick and easier start?
